language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
## Build
  - docker build -t udagram-api-feed:v4 ./udagram-api-feed
  - docker build -t udagram-api-user:v4 ./udagram-api-user
  - docker build -t udagram-frontend:v7 ./udagram-frontend
  - docker build -t udagram-reverseproxy:v4 ./udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed thienphuoc1990/udagram-api-feed:v4
  - docker tag udagram-api-user thienphuoc1990/udagram-api-user:v4
  - docker tag udagram-frontend thienphuoc1990/udagram-frontend:v7
  - docker tag udagram-reverseproxy thienphuoc1990/udagram-reverseproxy:v4

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thienphuoc1990/udagram-api-feed:v4
  - docker push thienphuoc1990/udagram-api-user:v4
  - docker push thienphuoc1990/udagram-frontend:v7
  - docker push thienphuoc1990/udagram-reverseproxy:v4