apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: thienphuoc1990/udagram-api-user:v5
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: global
          - secretRef:
              name: postgres
          - secretRef:
              name: aws
