apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user-deployment
  template:
    metadata:
      labels:
        app: backend-user-deployment
    spec:
      containers:
      - name: backend-user
        image: thienphuoc1990/udagram-api-user:v6
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: global
          - secretRef:
              name: postgres
          - secretRef:
              name: aws
