apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
  labels:
    app: backend-feed-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed-deployment
  template:
    metadata:
      labels:
        app: backend-feed-deployment
    spec:
      containers:
      - name: backend-feed
        image: thienphuoc1990/udagram-api-feed:v6
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: global
          - secretRef:
              name: postgres
          - secretRef:
              name: aws
